### ISSUE TITLE
Ejection simulation code

### ISSUE THREAD

**Issue by upavloff** [benjaminion/upgrading-ethereum-book#19]
Your *Ejection simulation code* does not take the inactivity score, and I don't see why. 

So, if it's a mistake, the code should replace the `epoch` with the `inactivity_score` in the while loop.

```python
GWEI = 10 ** 9
EJECTION_BALANCE = 16 * GWEI
MAX_EFFECTIVE_BALANCE = 32 * GWEI
HYSTERESIS_QUOTIENT = 4
INACTIVITY_PENALTY_QUOTIENT = 2 ** 24

# Simplified hysteresis for monotonically decreasing balance
def calc_effective_balance(balance):
    return min(MAX_EFFECTIVE_BALANCE, (balance + GWEI // HYSTERESIS_QUOTIENT) // GWEI * GWEI)

epoch = 0
balance = 32 * GWEI
effective_balance = calc_effective_balance(balance)
inactivity_score = 0

while effective_balance > EJECTION_BALANCE:
    balance -= effective_balance * inactivity_score // INACTIVITY_PENALTY_QUOTIENT
    effective_balance = calc_effective_balance(balance)
    inactivity_score += 4
    epoch += 1

print(balance / GWEI)
print(effective_balance // GWEI)
print(epoch)
```

With this, an inactive validator is ejected in **2344 epochs** instead of 4686. 
(And that's without taking into account the penalties due to missing attestations, but that's not the focus here it seems)

**Comment by benjaminion** [comment]
Hi, thanks for the feedback. I think the code in the book does give the correct answer, but it could be clearer since I took some shortcuts.

1. The inactivity score is just `INACTIVITY_SCORE_BIAS * epoch`, so my code accounts for that in the `balance -= effective_balance * epoch // INACTIVITY_PENALTY_QUOTIENT` line.
2. `INACTIVITY_SCORE_BIAS` does not appear in that line because it is in both the denominator and the numerator so it cancels out - your code is missing this.

See [here](https://eth2book.info/capella/part3/transition/epoch/#inactivity-penalty-deltas) for where `INACTIVITY_SCORE_BIAS` appears in the denominator.

I'll update the code to surface `INACTIVITY_SCORE_BIAS` explicitly. Apologies for the unclarity.

**Comment by upavloff** [comment]
You're right I didn't notice the `INACTIVITY_SCORE_BIAS` in the denominator, my bad! Sorry for the confusion.
