### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by rzmahmood** [benjaminion/upgrading-ethereum-book#22]
In section https://eth2book.info/capella/part3/config/preset/#withdrawals-processing

wold -> would

Thanks for making the book!

> This preset constant was introduced in the [Capella upgrade](https://eth2book.info/capella/part4/history/capella/) to bound the amount of work each node wold need to do when processing withdrawals.

**Comment by benjaminion** [comment]
Many thanks! Now [fixed](https://github.com/benjaminion/upgrading-ethereum-book/commit/b9ff3d15811c0ae0d7dd30621f128cbd82f21938). WIll go live next time I publish an update.

This slipped past the spell check due to a "wold" being

> a piece of high, open uncultivated land or moor.

Fun fact: I will be visiting the [Cotswolds](https://en.wikipedia.org/wiki/Cotswolds) in a couple of weeks.
